<?php

namespace App\Support;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\RateLimiter;

/**
 * Server-authoritative one-time-code store for the forgot-password wizard.
 *
 * The code is generated by {@see Otp}, stored HASHED in the session (never
 * plaintext), expires, is single-use, and the verify step is attempt-capped —
 * so possession of the email (where the code is sent) is required to reset the
 * password. NIK is an additional factor only when the account has one on file
 * (the team's C1 fix: NIK alone — a low-entropy, partly-public number — must
 * never be sufficient to reset a password).
 */
class PasswordResetOtp
{
    private const SESSION_KEY = 'pw_reset';

    private const TTL_SECONDS = 600;   // 10 minutes

    private const MAX_ATTEMPTS = 5;    // verify attempts before the code is burned

    /**
     * Issue a code for the user and store its hash. Returns the plaintext code
     * (to be emailed), or null when the per-account issue rate limit is hit.
     */
    public static function issue(User $user): ?string
    {
        $key = 'pw-reset-issue:'.$user->id;

        if (RateLimiter::tooManyAttempts($key, 3)) {
            return null; // at most 3 codes / 15 min / account
        }

        RateLimiter::hit($key, 900);

        $code = Otp::code();

        session()->put(self::SESSION_KEY, [
            'user_id' => $user->id,
            'hash' => Hash::make($code),
            'expires_at' => now()->addSeconds(self::TTL_SECONDS)->timestamp,
            'attempts' => 0,
            'verified' => false,
        ]);

        return $code;
    }

    /**
     * Verify the emailed code plus the NIK (when the account has one on file).
     * Increments the attempt counter and burns the code once exhausted.
     */
    public static function verify(string $code, ?string $nik): bool
    {
        $state = session(self::SESSION_KEY);

        if (! is_array($state)
            || now()->timestamp > $state['expires_at']
            || $state['attempts'] >= self::MAX_ATTEMPTS) {
            session()->forget(self::SESSION_KEY);

            return false;
        }

        $state['attempts']++;
        session()->put(self::SESSION_KEY, $state);

        $user = User::find($state['user_id']);

        if (! $user) {
            return false;
        }

        $codeOk = Hash::check($code, $state['hash']);
        // Constant-time NIK compare; skipped when the account has no NIK on file.
        $nikOk = blank($user->nik) || hash_equals((string) $user->nik, (string) $nik);

        if ($codeOk && $nikOk) {
            $state['verified'] = true;
            session()->put(self::SESSION_KEY, $state);

            return true;
        }

        return false;
    }

    /** The user whose code+NIK have been verified this session, or null. */
    public static function verifiedUser(): ?User
    {
        $state = session(self::SESSION_KEY);

        return (is_array($state) && ($state['verified'] ?? false))
            ? User::find($state['user_id'])
            : null;
    }

    /** Whether the in-flight account requires a NIK at the verify step. */
    public static function requiresNik(): bool
    {
        $state = session(self::SESSION_KEY);

        if (! is_array($state)) {
            return false;
        }

        return (bool) optional(User::find($state['user_id']))->nik;
    }

    public static function clear(): void
    {
        session()->forget(self::SESSION_KEY);
    }
}
